spring:
  application:
    name: gestor-tareas-api
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  messages:
    basename: messages
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework: info
